version: "3.8"

services:
  app:
    container_name: hsl-timetable
    image: hsl-timetable
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 5000:3000
